const data = [
  { "No.": 1, "Problem": "Map Polyfill", "Difficulty": "Easy", "Status": "Unsolved" },
  { "No.": 2, "Problem": "React Counter", "Difficulty": "Easy", "Status": "Attempted" },
  { "No.": 3, "Problem": "Debounce Function", "Difficulty": "Medium", "Status": "Unsolved" },
  { "No.": 4, "Problem": "Throttle Function", "Difficulty": "Medium", "Status": "Unsolved" },
  { "No.": 5, "Problem": "React Todo List", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 6, "Problem": "Resize Hook", "Difficulty": "Medium", "Status": "Attempted" },
  { "No.": 7, "Problem": "usePrevious Hook", "Difficulty": "Medium", "Status": "Unsolved" },
  { "No.": 8, "Problem": "Theme Context", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 9, "Problem": "React Accordion", "Difficulty": "Medium", "Status": "Unsolved" },
  { "No.": 10, "Problem": "React Modal", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 11, "Problem": "Promise Polyfill", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 12, "Problem": "Virtual List", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 13, "Problem": "Form Validation", "Difficulty": "Medium", "Status": "Attempted" },
  { "No.": 14, "Problem": "Stopwatch", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 15, "Problem": "useFetch Hook", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 16, "Problem": "useDebounce Hook", "Difficulty": "Medium", "Status": "Attempted" },
  { "No.": 17, "Problem": "Image Carousel", "Difficulty": "Medium", "Status": "Unsolved" },
  { "No.": 18, "Problem": "Infinite Scroll", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 19, "Problem": "Form Builder", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 20, "Problem": "Theme Toggle", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 21, "Problem": "Outside Click", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 22, "Problem": "Protected Routes", "Difficulty": "Medium", "Status": "Attempted" },
  { "No.": 23, "Problem": "Sort by Key", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 24, "Problem": "Deep Clone", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 25, "Problem": "Flatten Array", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 26, "Problem": "Palindrome Check", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 27, "Problem": "Drag and Drop", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 28, "Problem": "Tabs Component", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 29, "Problem": "Memoization", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 30, "Problem": "Dropdown", "Difficulty": "Medium", "Status": "Attempted" },
  { "No.": 31, "Problem": "Weather App", "Difficulty": "Easy", "Status": "Attempted" },
  { "No.": 32, "Problem": "Anagram Check", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 33, "Problem": "React Optimization", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 34, "Problem": "Event Delegation", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 35, "Problem": "React Table Filter", "Difficulty": "Medium", "Status": "Attempted" },
  { "No.": 36, "Problem": "Call, Apply, Bind", "Difficulty": "Hard", "Status": "Attempted" },
  { "No.": 37, "Problem": "Responsive Navbar", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 38, "Problem": "Sticky Header", "Difficulty": "Medium", "Status": "Unsolved" },
  { "No.": 39, "Problem": "Lazy Load Image", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 40, "Problem": "Currying", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 41, "Problem": "Countdown Timer", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 42, "Problem": "Step Wizard", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 43, "Problem": "Rating Component", "Difficulty": "Medium", "Status": "Attempted" },
  { "No.": 44, "Problem": "JSON Table", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 45, "Problem": "stringify Polyfill", "Difficulty": "Hard", "Status": "Unsolved" },
  { "No.": 46, "Problem": "Login Form", "Difficulty": "Medium", "Status": "Solved" },
  { "No.": 47, "Problem": "React LocalStorage", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 48, "Problem": "Copy to Clipboard", "Difficulty": "Easy", "Status": "Solved" },
  { "No.": 49, "Problem": "Object.create Polyfill", "Difficulty": "Medium", "Status": "Attempted" },
  { "No.": 50, "Problem": "Chat UI", "Difficulty": "Medium", "Status": "Unsolved" }
];

export default data;
